import { useState } from 'react'
import { Download, FolderOpen, Pencil, RefreshCw, Search, Trash2, Upload } from 'lucide-react'
import type { DeletionImpact, MediaKind, WorkbenchAPI, WorkbenchAsset, WorkbenchSnapshot } from '../../shared/workbench-types'
import { PROVIDER_NAMES } from '../../shared/workbench-types'
import type { Provider } from '../../shared/types'
import { deselectSelection, selectAvailable } from '../selection'
import type { WorkspaceStore } from '../useWorkspace'
import { Banner, EmptyState, ImpactDialog, Pager, RenameDialog, duration, useAction } from './Common'
import { Dialog } from './Dialog'
import { LibraryThumbnail } from './LibraryMedia'
import { UsageSelect, matchesUsage, usageLabel } from './AssetSelector'
import type { UsageFilter } from './AssetSelector'

export function LibraryWorkspace({ data, store, onPreview }: { data: WorkbenchSnapshot; store: WorkspaceStore; onPreview: (asset: WorkbenchAsset) => void }) {
  const [kind, setKind] = useState<MediaKind>('audio')
  const [search, setSearch] = useState('')
  const [filter, setFilter] = useState<UsageFilter>('all')
  const [page, setPage] = useState(0)
  const [selected, setSelected] = useState<Set<string>>(new Set())
  const [rename, setRename] = useState<WorkbenchAsset>()
  const [impact, setImpact] = useState<DeletionImpact>()
  const [imports, setImports] = useState<Awaited<ReturnType<WorkbenchAPI['importAssets']>>>()
  const action = useAction()
  const filtered = data.assets.filter(a => a.kind === kind && a.name.toLocaleLowerCase().includes(search.toLocaleLowerCase()) && matchesUsage(a, filter))
  const current = Math.min(page, Math.max(0, Math.ceil(filtered.length / 20) - 1))
  const visible = filtered.slice(current * 20, current * 20 + 20)
  const selectedAssets = data.assets.filter(a => selected.has(a.id))
  const selectedInFilter = filtered.filter(asset => selected.has(asset.id)).length
  async function exportOne(asset: WorkbenchAsset): Promise<void> { const path = await window.canvas.exportAsset(asset.id); store.notify(path ? `已另存：${path}` : '已取消另存', path ? 'success' : 'info') }
  return <div className="standalone-page stack" data-testid="library-workspace">
    <header className="page-header"><div><h1>素材库</h1><p className="meta">统一管理音乐、图片与成片；项目删除不影响素材和使用记录。</p></div><button className="button" data-testid="library-refresh" disabled={action.busy} onClick={() => void action.run(async () => { await window.canvas.refreshAssets(); await store.refresh(); store.notify('素材状态已刷新') })}><RefreshCw size={17} />刷新</button></header>
    <div className="tabs" aria-label="素材分类">{(['audio', 'image', 'video'] as const).map(tab => <button className="tab" key={tab} data-testid={`library-tab-${tab}`} aria-pressed={kind === tab} onClick={() => { setKind(tab); setPage(0) }}>{({ audio: '音乐', image: '图片', video: '视频' })[tab]}<span className="meta">{data.assets.filter(a => a.kind === tab).length}</span></button>)}</div>
    <div className="toolbar"><label className="search-field"><Search size={17} /><input data-testid="library-search" aria-label="搜索素材" value={search} placeholder="搜索素材名称" onChange={e => { setSearch(e.target.value); setPage(0) }} /></label><UsageSelect value={filter} onChange={value => { setFilter(value); setPage(0) }} />{kind !== 'video' && <button className="button" data-testid="library-import" disabled={action.busy} onClick={() => void action.run(async () => { const result = await window.canvas.importAssets(kind); setImports(result); await store.refresh() })}><Upload size={17} />导入{kind === 'audio' ? '音乐' : '图片'}</button>}</div>
    {action.error && <Banner tone="error">{action.error}</Banner>}
    <div className="section-row"><div className="button-row"><button className="button" data-testid="library-select-all" disabled={action.busy || !filtered.some(asset => asset.available)} onClick={() => setSelected(old => new Set(selectAvailable([...old], filtered)))}>全选筛选结果</button><button className="button" data-testid="library-deselect-all" disabled={action.busy || !selectedInFilter} onClick={() => setSelected(old => new Set(deselectSelection([...old], filtered.map(asset => asset.id))))}>全取消筛选结果</button></div><p className="meta">{filtered.length} 个匹配素材 · 当前筛选已选 {selectedInFilter} · 全部分页 / 分类累计已选 {selectedAssets.length} 项</p><button className="button" data-testid="library-export-selected" disabled={action.busy || !selectedAssets.some(a => a.available)} onClick={() => void action.run(async () => { for (const asset of selectedAssets.filter(a => a.available)) await exportOne(asset) })}>另存选中</button></div>
    <div><button className="text-button" data-testid="library-clear-all" disabled={!selectedAssets.length || action.busy} onClick={() => setSelected(new Set())}>清空全部已选（所有分类）</button></div>
    {!filtered.length ? <EmptyState title={data.assets.some(a => a.kind === kind) ? '没有匹配素材' : `暂无${({ audio: '音乐', image: '图片', video: '视频' })[kind]}`}>{kind === 'video' ? '成功合成并发布的成片会自动登记在这里。' : '导入本地文件，或在素材生成中创建。重复文件由资产层识别。'}</EmptyState> : <div className="asset-list">{visible.map(asset => <article className={`asset-row ${selected.has(asset.id) ? 'selected' : ''}`} key={asset.id} data-testid={`asset-${asset.id}`}>
      <div className="asset-main"><input type="checkbox" aria-label={`选择 ${asset.name}`} checked={selected.has(asset.id)} disabled={!asset.available && !selected.has(asset.id)} onChange={e => setSelected(old => { const next = new Set(old); if (e.target.checked) next.add(asset.id); else next.delete(asset.id); return next })} />{asset.kind === 'image' && <LibraryThumbnail id={asset.id} name={asset.name} available={asset.available} />}<div className="asset-name"><strong>{asset.name}</strong><p className="meta">{asset.kind === 'image' ? `${asset.width ?? '—'} × ${asset.height ?? '—'}` : duration(asset.durationSeconds)} · {asset.format?.toUpperCase() ?? '本地文件'} · {usageLabel(asset)}</p>{!asset.available && <p className="error-text meta">{asset.problem ?? '文件不可用'}</p>}</div><div className="button-row"><button className="button" data-testid={`asset-preview-${asset.id}`} onClick={() => onPreview(asset)}>{asset.kind === 'audio' ? '试听' : asset.kind === 'image' ? '查看' : '播放'}</button><button className="icon-button" aria-label={`另存 ${asset.name}`} disabled={action.busy || !asset.available} onClick={() => void action.run(() => exportOne(asset))}><Download size={17} /></button><button className="icon-button" aria-label={`打开 ${asset.name} 文件位置`} disabled={action.busy || !asset.available} onClick={() => void action.run(async () => { await window.canvas.revealAsset(asset.id); store.notify('已打开文件位置') })}><FolderOpen size={17} /></button><button className="icon-button" data-testid={`asset-rename-${asset.id}`} aria-label={`重命名 ${asset.name}`} onClick={() => setRename(asset)}><Pencil size={17} /></button><button className="icon-button danger" data-testid={`asset-delete-${asset.id}`} aria-label={`删除 ${asset.name}`} disabled={action.busy} onClick={() => void action.run(async () => setImpact(await window.canvas.assetImpact(asset.id)))}><Trash2 size={17} /></button></div></div>
      <details className="asset-details"><summary>来源与使用记录</summary><div className="details-columns"><section><h3>来源快照</h3>{asset.origins.length ? <ul>{asset.origins.map((origin, i) => <li key={i}>{origin.name}{origin.provider ? ` · ${PROVIDER_NAMES[origin.provider as Provider] ?? origin.provider}` : ''}{origin.model ? ` · ${origin.model}` : ''}</li>)}</ul> : <p className="meta">来源未登记</p>}</section><section><h3>成功使用 · {asset.usedCount}</h3>{asset.usages.length ? <ul>{asset.usages.map(use => <li key={use.id}>{use.name} · {duration(use.durationSeconds)}<p className="meta">{new Date(use.finishedAt).toLocaleString('zh-CN')}{use.uncertain ? ' · 待核对' : ''}</p></li>)}</ul> : <p className="meta">{asset.historyUncertain ? '旧记录无法可靠还原，不计为未使用。' : '没有成功使用记录，试听或规划不计为使用。'}</p>}</section></div></details>
    </article>)}</div>}
    <Pager page={current} total={filtered.length} onChange={setPage} />
    {rename && <RenameDialog name={rename.name} onClose={() => setRename(undefined)} onSave={async name => { await window.canvas.renameAsset(rename.id, name); await store.refresh() }} />}
    {impact && <ImpactDialog impact={impact} entity="asset" onClose={() => setImpact(undefined)} onDelete={async () => { await window.canvas.deleteAsset(impact.id); await store.refresh(); setSelected(old => new Set([...old].filter(id => id !== impact.id))); store.notify('素材已删除，外部原件和历史使用记录保留') }} />}
    {imports && <Dialog title="导入结果" onClose={() => setImports(undefined)}><div className="dialog-body stack">{imports.cancelled ? <p>已取消文件选择。</p> : <><p>{imports.entries.filter(e => e.status === 'imported').length} 已导入 · {imports.entries.filter(e => e.status === 'duplicate').length} 重复 · {imports.entries.filter(e => e.status === 'failed').length} 失败</p><ul className="import-results">{imports.entries.map((entry, i) => <li key={i}><strong>{entry.name}</strong><p className={entry.status === 'failed' ? 'error-text' : 'meta'}>{entry.status === 'imported' ? '已导入' : entry.status === 'duplicate' ? '已存在，没有重复复制' : entry.error ?? '导入失败'}</p></li>)}</ul></>}</div><footer className="dialog-footer"><button className="button primary" onClick={() => setImports(undefined)}>完成</button></footer></Dialog>}
  </div>
}
