import { useState } from 'react'
import { FolderOpen, Plus, ShieldCheck } from 'lucide-react'
import type { ApiConfiguration, ApiConfigurationInput, DeletionImpact, RenderSettings, WorkbenchAPI, WorkbenchSnapshot } from '../../shared/workbench-types'
import { PROVIDER_NAMES } from '../../shared/workbench-types'
import { apiInputSchema, renderSettingsSchema } from '../../shared/workbench-schemas'
import type { Provider } from '../../shared/types'
import { isLanAceStepURL, normalizedAceStepURL } from '../../shared/music-schemas'
import { isMurekaProvider, MUREKA_ORIGINS } from '../../shared/music-capabilities'
import type { WorkspaceStore } from '../useWorkspace'
import { Banner, EmptyState, ImpactDialog, useAction } from './Common'
import { Dialog } from './Dialog'
import { NumberField } from './CompositionParameters'
import { useAceStepModels } from '../hooks/useAceStepModels'
import { AceStepStatus } from './AceStepStatus'

function ApiEditor({ configuration, providers, encryptionAvailable, onClose, onSaved }: { configuration?: ApiConfiguration; providers: Provider[]; encryptionAvailable: boolean; onClose: () => void; onSaved: () => Promise<void> }) {
  const [provider, setProvider] = useState<Provider>(configuration?.provider ?? providers[0])
  const [key, setKey] = useState('')
  const [clearKey, setClearKey] = useState(false)
  const [local, setLocal] = useState({ baseUrl: configuration?.local?.baseUrl ?? 'http://127.0.0.1:8001', waitMinutes: configuration?.local?.waitMinutes ?? 60, allowLan: configuration?.local?.allowLan ?? false })
  const [acknowledged, setAcknowledged] = useState(false)
  const [discard, setDiscard] = useState(false)
  const [check, setCheck] = useState<string>()
  const action = useAction()
  const isLocal = provider === 'acestep'
  const addressChanged = Boolean(configuration?.local && normalizedAceStepURL(local.baseUrl) !== configuration.local.baseUrl)
  const input: ApiConfigurationInput = { provider, ...(key && !clearKey ? { key } : {}), ...(clearKey ? { clearKey: true } : {}), ...(isLocal ? { local } : {}) }
  const parsed = apiInputSchema.safeParse(input)
  const dirty = Boolean(key || clearKey || isLocal && (local.baseUrl !== (configuration?.local?.baseUrl ?? 'http://127.0.0.1:8001') || local.waitMinutes !== (configuration?.local?.waitMinutes ?? 60) || local.allowLan !== (configuration?.local?.allowLan ?? false)))
  const validSave = parsed.success && (!addressChanged || acknowledged) && (isLocal || Boolean(key) || Boolean(configuration)) && (!key || encryptionAvailable)
  const testPossible = parsed.success && (!addressChanged || acknowledged) && (isLocal || Boolean(key) || Boolean(configuration?.hasKey && !clearKey))
  function close(): void { if (dirty && !discard) setDiscard(true); else { setKey(''); onClose() } }
  return <Dialog title={configuration ? `编辑 ${PROVIDER_NAMES[provider]}` : '添加 API'} busy={action.busy} onClose={close}>
    <form onSubmit={e => { e.preventDefault(); if (validSave) void action.run(async () => { await window.canvas.saveApi(input); setKey(''); await onSaved(); onClose() }) }}><div className="dialog-body stack">
      {discard && <Banner tone="warning">关闭会丢弃未保存的连接与密钥输入。<div className="button-row"><button type="button" className="button danger" onClick={() => { setKey(''); onClose() }}>放弃并关闭</button><button type="button" className="button" onClick={() => setDiscard(false)}>继续编辑</button></div></Banner>}
      <label className="field">厂商<select data-testid="api-provider" value={provider} disabled={Boolean(configuration) || action.busy} onChange={e => { setProvider(e.target.value as Provider); setKey(''); setClearKey(false); setCheck(undefined) }}>{providers.map(p => <option key={p} value={p}>{PROVIDER_NAMES[p]} · {p === 'siliconflow' ? '图片' : '音乐'}</option>)}</select><span className="meta">同厂商只能添加一个配置。只列出尚未添加的厂商。</span></label>
      {isMurekaProvider(provider) && <p className="meta">{MUREKA_ORIGINS[provider]} · 国内站与国际站各一个配置、密钥互不通用；不会自动切站或跨站重发。</p>}
      {isLocal && <><p className="meta">连接自行部署的 ACE-Step REST API，不安装或启动模型。无密钥也可添加本地配置。</p><label className="field">服务根地址<input data-testid="api-local-url" value={local.baseUrl} disabled={action.busy} autoComplete="off" spellCheck={false} onChange={e => { setLocal(old => ({ ...old, baseUrl: e.target.value, allowLan: false })); setAcknowledged(false); setCheck(undefined) }} placeholder="http://127.0.0.1:8001" /><span className="meta">填写 API 端口，不是网页端口；环回或已确认的私有 IP，不含路径。</span></label><NumberField label="查询等待上限 · 分钟" value={local.waitMinutes} min={5} max={180} disabled={action.busy} note="5–180 分钟；到时只暂停查询，保留远端任务 ID，不自动重发" onChange={value => setLocal(old => ({ ...old, waitMinutes: value }))} />{isLanAceStepURL(local.baseUrl) && <label className="checkbox-label"><input type="checkbox" checked={local.allowLan} disabled={action.busy} onChange={e => setLocal(old => ({ ...old, allowLan: e.target.checked }))} />确认连接局域网目标 {local.baseUrl}。HTTP 明文可能暴露歌词与密钥，仅用于可信网络；不绕过 TLS 验证。</label>}{addressChanged && <Banner tone="warning"><p>更换地址会重置连接身份并清除原连接密钥。未完成任务仍绑定旧连接，可能阻止更换；新地址需要鉴权时请填写新的密钥。</p><label className="checkbox-label"><input type="checkbox" checked={acknowledged} disabled={action.busy} onChange={e => setAcknowledged(e.target.checked)} />确认更换连接并清除旧地址凭据</label></Banner>}</>}
      <label className="field">{isLocal ? 'API 密钥 · 可选' : configuration ? '替换密钥 · 留空保持' : 'API 密钥'}<input data-testid="api-key" type="password" value={key} disabled={action.busy || clearKey || !encryptionAvailable} autoComplete="new-password" spellCheck={false} autoCapitalize="off" onChange={e => { setKey(e.target.value); setCheck(undefined) }} placeholder={configuration?.hasKey ? '已保存，留空不修改' : isLocal ? '服务未启用鉴权时留空' : '粘贴密钥'} /><span className="meta">只在系统加密存储中保存；不回显、不写浏览器持久存储或日志。</span></label>
      {configuration?.hasKey && <label className="checkbox-label"><input data-testid="api-clear-key" type="checkbox" checked={clearKey} disabled={action.busy} onChange={e => { setClearKey(e.target.checked); setKey(''); setCheck(undefined) }} />明确清除已保存密钥（保存后生效，云端生成将不可用）</label>}
      {!encryptionAvailable && <Banner tone="warning">系统加密不可用，不能保存密钥，不降级为明文；无密钥本地连接仍可添加。</Banner>}
      <p className="meta">测试使用当前输入，未保存也能测试。只读检查账户 / 健康 / 模型，不创建生成请求，不验证实际出曲或生图能力。</p>
      {!parsed.success && <p className="error-text" role="alert">{parsed.error.issues.map(i => i.message).slice(0, 3).join('；')}</p>}{check && <Banner tone="success">{check}</Banner>}{action.error && <Banner tone="error">{action.error}</Banner>}
    </div><footer className="dialog-footer"><button type="button" className="button" disabled={action.busy} onClick={close}>取消</button><button type="button" className="button" data-testid="api-test" disabled={action.busy || !testPossible} onClick={() => void action.run(async () => { setCheck(undefined); const result = await window.canvas.testApi(input); setCheck(result.message) })}>{action.busy ? '处理中…' : '测试当前输入（只读）'}</button><button className="button primary" data-testid="api-save" disabled={action.busy || !validSave}>{configuration ? '保存修改' : '添加 API'}</button></footer></form>
  </Dialog>
}
function RenderPreferences({ data, store }: { data: WorkbenchSnapshot; store: WorkspaceStore }) {
  const [render, setRender] = useState<RenderSettings>(data.settings.render)
  const [tools, setTools] = useState<Awaited<ReturnType<WorkbenchAPI['checkVideoTools']>>>()
  const action = useAction()
  const parsed = renderSettingsSchema.safeParse(render)
  return <div className="stack settings-section"><h2>全局合成调度</h2><p className="meta">跨合成项目共享任务池。实际并行受可用内存、总线程、GPU 会话及临时磁盘预算限制；资源不足会排队并说明原因。</p><form className="stack" onSubmit={e => { e.preventDefault(); if (parsed.success) void action.run(async () => { await window.canvas.updateSettings({ render: parsed.data }); await store.refresh(); store.notify('全局合成设置已保存') }) }}><div className="form-grid"><NumberField label="目标并行任务" testId="render-concurrency" value={render.concurrency} min={1} max={4} onChange={value => setRender(old => ({ ...old, concurrency: value }))} /><NumberField label="每任务线程上限" testId="render-threads" value={render.threads} min={1} max={16} onChange={value => setRender(old => ({ ...old, threads: value }))} /><label className="field">编码器<select data-testid="render-encoder" value={render.encoder} onChange={e => setRender(old => ({ ...old, encoder: e.target.value as RenderSettings['encoder'] }))}><option value="auto">自动 · 根据实际可用性选择</option><option value="cpu">CPU · libx264</option><option value="nvenc">NVIDIA NVENC</option><option value="qsv">Intel QSV</option></select></label></div><p className="meta">静态图片连续编码完整画面，音乐完整播放一次，不循环音乐、不裁歌。硬件编码须通过实际初始化检查；不可用时说明原因并回退 CPU。</p>{!parsed.success && <p className="error-text">并行须为 1–4 整数，每任务线程须为 1–16 整数。</p>}<div><button className="button primary" data-testid="render-save" disabled={action.busy || !parsed.success}>保存合成设置</button></div></form>
    <section className="stack tools-section"><h2>FFmpeg 与编码能力</h2><p className="meta">{data.settings.ffmpegPath ?? '自动查找 FFmpeg / FFprobe'}</p><div className="button-row"><button className="button" data-testid="tools-check" disabled={action.busy} onClick={() => void action.run(async () => setTools(await window.canvas.checkVideoTools()))}>{action.busy ? '检测中…' : '实际检测工具与编码器'}</button><button className="button" disabled={action.busy} onClick={() => void action.run(async () => { await window.canvas.chooseFFmpeg(); setTools(undefined); await store.refresh() })}>选择 FFmpeg</button><button className="text-button" disabled={action.busy || !data.settings.ffmpegPath} onClick={() => void action.run(async () => { await window.canvas.resetFFmpeg(); setTools(undefined); await store.refresh() })}>恢复自动查找</button></div>{tools ? <><Banner tone={tools.available ? 'success' : 'warning'}>{tools.message}</Banner><dl className="key-values"><dt>FFmpeg</dt><dd>{tools.ffmpeg ?? '未找到'}</dd><dt>FFprobe</dt><dd>{tools.ffprobe ?? '未找到'}</dd><dt>版本</dt><dd>{tools.version ?? '未报告'}</dd></dl>{tools.encoders?.map(encoder => <p key={encoder.encoder} className={encoder.available ? 'meta' : 'warning-text'}>{encoder.encoder} · {encoder.available ? '可用' : '不可用'} · {encoder.message}</p>)}</> : <p className="meta">尚未检测。编码器列在列表中不等于实际可用。</p>}</section>{action.error && <Banner tone="error">{action.error}</Banner>}
  </div>
}
export function SettingsWorkspace({ data, store }: { data: WorkbenchSnapshot; store: WorkspaceStore }) {
  const [tab, setTab] = useState<'apis' | 'render' | 'storage'>('apis')
  const [editing, setEditing] = useState<{ configuration?: ApiConfiguration }>()
  const [impact, setImpact] = useState<{ value: DeletionImpact; provider: Provider }>()
  const action = useAction()
  const ace = useAceStepModels(data.apis.find(api => api.provider === 'acestep'))
  const available = (Object.keys(PROVIDER_NAMES) as Provider[]).filter(p => !data.apis.some(api => api.provider === p))
  return <div className="standalone-page stack" data-testid="settings-workspace"><header className="page-header"><div><h1>设置</h1><p className="meta">管理已添加 API、本地合成资源与存储位置。</p></div></header><div className="tabs" aria-label="设置类别">{([{ id: 'apis', label: 'API 配置' }, { id: 'render', label: '合成与工具' }, { id: 'storage', label: '存储位置' }] as const).map(item => <button className="tab" data-testid={`settings-tab-${item.id}`} key={item.id} aria-pressed={tab === item.id} onClick={() => setTab(item.id)}>{item.label}</button>)}</div>
    {tab === 'apis' && <section className="stack settings-section"><div className="section-row"><h2>已添加 API</h2><button className="button primary" data-testid="api-add" disabled={!available.length} onClick={() => setEditing({})}><Plus size={17} />添加 API</button></div><p className="security-note meta"><ShieldCheck size={18} />{data.encryptionAvailable ? '系统加密可用 · 密钥不回显' : '系统加密不可用 · 禁止明文保存密钥'}</p>{!data.apis.length ? <EmptyState title="尚未添加 API">先添加要使用的厂商；没有配置不会显示为已连接。本地 ACE-Step 可无密钥添加。</EmptyState> : <div className="api-list">{data.apis.map(api => <article className="api-row" key={api.provider}><div className="section-row"><div><h3>{PROVIDER_NAMES[api.provider]}</h3><p className="meta">{api.kind === 'audio' ? '音乐' : '图片'} · {api.hasKey ? '已保存密钥' : api.provider === 'acestep' ? '无密钥本地连接' : '未保存密钥'}{api.local ? ` · ${api.local.baseUrl}` : ''}</p></div><div className="button-row"><button className="button" data-testid={`api-edit-${api.provider}`} onClick={() => setEditing({ configuration: api })}>编辑 / 测试</button><button className="text-button danger" data-testid={`api-delete-${api.provider}`} disabled={action.busy} onClick={() => void action.run(async () => setImpact({ provider: api.provider, value: await window.canvas.apiImpact(api.provider) }))}>删除</button></div></div>{api.lastCheck ? <p className={`meta ${api.lastCheck.ok ? '' : 'error-text'}`}>{new Date(api.lastCheck.at).toLocaleString('zh-CN')} · {api.lastCheck.message}</p> : <p className="meta">尚未测试，不代表连接已就绪。</p>}{api.provider === 'acestep' && <div className="stack"><div><button className="text-button" data-testid="settings-ace-models" disabled={ace.checking} onClick={() => void ace.refresh()}>{ace.checking ? '读取中…' : '读取已保存连接模型（只读）'}</button></div>{ace.status && <AceStepStatus status={ace.status} />}{ace.error && <Banner tone="error">{ace.error}</Banner>}</div>}</article>)}</div>}</section>}
    {tab === 'render' && <RenderPreferences data={data} store={store} />}
    {tab === 'storage' && <section className="stack settings-section"><h2>媒体保存位置</h2><p className="path-value">{data.settings.mediaRoot}</p><p className="meta">素材由独立资产层管理，不依赖项目存活。仅通过系统目录选择器更换，不接受任意路径提交。已有文件是否可迁移由存储层检查。</p><div><button className="button" data-testid="storage-choose-root" disabled={action.busy} onClick={() => void action.run(async () => { const result = await window.canvas.chooseMediaRoot(); await store.refresh(); store.notify(result ? '媒体保存位置已更新' : '已取消选择', result ? 'success' : 'info') })}><FolderOpen size={17} />选择媒体目录</button></div><Banner>删除项目只删除工作区元数据；删除媒体请在素材库查看关联影响并确认。外部原件、另存副本与历史使用台账不会随资产删除。</Banner></section>}
    {action.error && <Banner tone="error">{action.error}</Banner>}
    {editing && <ApiEditor configuration={editing.configuration} providers={editing.configuration ? [editing.configuration.provider] : available} encryptionAvailable={data.encryptionAvailable} onClose={() => setEditing(undefined)} onSaved={async () => { await store.refresh(); store.notify('API 配置已保存') }} />}
    {impact && <ImpactDialog impact={impact.value} entity="api" onClose={() => setImpact(undefined)} onDelete={async () => { await window.canvas.deleteApi(impact.provider); await store.refresh() }} />}
  </div>
}
