import { expect, test, type ElectronApplication } from '@playwright/test'
import { mkdir } from 'node:fs/promises'
import path from 'node:path'
import { addApi, addEntry, assertV4Isolation, assetBytes, close, confirmAction, createComposition, createGeneration, createProfile, deleteCurrent, digest, fileDigest, expectApiChoices, expectSecretAbsent, expandEntry, launch, nativeOpen, nativeSave, removeProfile, renameCurrent, scratchPath, snapshot, submitAll, updateStored } from './v4-helpers'

test('V4 desktop: empty APIs, independent A/B project drafts, CRUD, current items, native storage and restart', async () => {
  const directory = await createProfile('desktop-drafts')
  let app: ElectronApplication | undefined
  try {
    let running = await launch(directory); app = running.app; let page = running.page
    const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
    const empty = await snapshot(page)
    expect(empty.apis).toEqual([]); expect(empty.generationProjects).toEqual([]); expect(empty.compositionProjects).toEqual([]); expect(empty.assets).toEqual([])
    await assertV4Isolation(app, page)
    await page.getByTestId('nav-settings').click()
    await expect(page.getByRole('heading', { name: '尚未添加 API', exact: true })).toBeVisible()
    await page.getByTestId('api-add').click()
    const apiDialog = page.getByRole('dialog', { name: '添加 API', exact: true })
    await expect(apiDialog.getByTestId('api-save')).toBeDisabled()
    await expect(apiDialog.getByTestId('api-test')).toBeDisabled()
    await page.keyboard.press('Escape')
    await expect(page.getByTestId('api-add')).toBeFocused()

    const a = await createGeneration(page, '生成 A · 雨夜书房')
    const musicA = await addEntry(page, a.id, 'audio')
    const rowA = page.getByTestId(`entry-${musicA.id}`)
    await expectApiChoices(rowA, [])
    const longDraft = '未添加 API 也要完整保存的音乐草稿\n' + '雨夜、钢琴、长描述。'.repeat(260)
    await rowA.getByTestId('entry-prompt').fill(longDraft)
    await expect(page.getByLabel('生成次数', { exact: true })).toHaveCount(0)
    const imageA = await addEntry(page, a.id, 'image')
    await expectApiChoices(page.getByTestId(`entry-${imageA.id}`), [])
    await page.getByTestId(`entry-${imageA.id}`).getByTestId('entry-prompt').fill('A 窗边书桌，独立图片草稿')
    // No sleep: project switching must flush both kinds of incomplete drafts.
    const b = await createGeneration(page, '生成 B · 独立')
    expect(b.entryIds).toEqual([])
    await expect(page.locator('[data-testid^="entry-expand-"]')).toHaveCount(0)
    const musicB = await addEntry(page, b.id, 'audio')
    await page.getByTestId(`entry-${musicB.id}`).getByTestId('entry-prompt').fill('B 与 A 不同的音乐草稿')
    await page.getByTestId(`generation-project-${a.id}`).click()
    await expect(page.getByTestId('generation-tab-image')).toHaveAttribute('aria-pressed', 'true')
    await expect((await expandEntry(page, imageA.id)).getByTestId('entry-prompt')).toHaveValue('A 窗边书桌，独立图片草稿')
    await page.getByTestId('generation-tab-audio').click()
    await expect((await expandEntry(page, musicA.id)).getByTestId('entry-prompt')).toHaveValue(longDraft)
    const copy = await addEntry(page, a.id, 'audio', musicA.id)
    expect(copy.draft.prompt).toBe(longDraft); expect(copy.requestId).toBeUndefined()
    await page.getByTestId(`entry-delete-${copy.id}`).click()
    await confirmAction(page, '删除未提交条目？')
    await expect(page.getByTestId(`entry-${copy.id}`)).toHaveCount(0)
    await renameCurrent(page, '生成 A · 已重命名')
    const disposable = await createGeneration(page, '生成临时项目')
    await deleteCurrent(page)
    expect((await snapshot(page)).generationProjects.some(project => project.id === disposable.id)).toBe(false)

    const compositionA = await createComposition(page, '合成 A')
    await page.getByTestId('composition-minimum-minutes').fill('1')
    const compositionB = await createComposition(page, '合成 B')
    expect(compositionB.draft.audioIds).toEqual([]); expect(compositionB.draft.imageIds).toEqual([])
    await expect(page.getByTestId('composition-minimum-minutes')).toHaveValue('60')
    await page.getByTestId('composition-minimum-minutes').fill('2')
    await page.getByTestId(`composition-project-${compositionA.id}`).click()
    await expect(page.getByTestId('composition-minimum-minutes')).toHaveValue('1')
    await renameCurrent(page, '合成 A · 已重命名')
    const disposableComposition = await createComposition(page, '合成临时项目')
    await deleteCurrent(page)
    expect((await snapshot(page)).compositionProjects.some(project => project.id === disposableComposition.id)).toBe(false)
    await page.getByTestId(`composition-project-${compositionB.id}`).click()
    await expect(page.getByTestId('composition-minimum-minutes')).toHaveValue('2')
    await expect(page.getByTestId('composition-plan-button')).toBeDisabled()

    // Chooser-only root change is legal before any media/request exists; project drafts survive.
    const mediaRoot = path.join(directory, '新 素材保存位置'); await mkdir(mediaRoot)
    await nativeOpen(app, [mediaRoot])
    await page.getByTestId('nav-settings').click()
    await page.getByTestId('settings-tab-storage').click()
    await page.getByTestId('storage-choose-root').click()
    await expect.poll(async () => (await snapshot(page)).settings.mediaRoot).toBe(mediaRoot)
    await page.getByTestId('nav-generation').click()
    await page.getByTestId(`generation-project-${b.id}`).click()
    const current = await expandEntry(page, musicB.id)
    for (const [width, height] of [[1366, 768], [1920, 1080]]) {
      await app.evaluate(({ BrowserWindow }, size) => BrowserWindow.getAllWindows()[0].setSize(size[0], size[1]), [width, height])
      await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
      expect(await current.getByTestId('entry-prompt').evaluate(element => getComputedStyle(element).fontSize)).toBe('16px')
      expect(await page.getByTestId('project-name').evaluate(element => getComputedStyle(element).fontSize)).toBe('24px')
      await page.screenshot({ path: scratchPath(`v4-desktop-drafts-${width}.png`) })
    }
    expect(errors).toEqual([])
    await close(app); app = undefined
    running = await launch(directory); app = running.app; page = running.page
    const restored = await snapshot(page)
    expect(restored.settings).toMatchObject({ page: 'generation', lastGenerationId: b.id, lastCompositionId: compositionB.id, mediaRoot })
    expect(restored.generationProjects).toHaveLength(2); expect(restored.compositionProjects).toHaveLength(2); expect(restored.apis).toEqual([])
    expect(restored.entries.find(entry => entry.id === musicA.id)?.draft.prompt).toBe(longDraft)
    expect(restored.entries.find(entry => entry.id === imageA.id)?.draft.prompt).toBe('A 窗边书桌，独立图片草稿')
    await expect(page.getByTestId(`generation-project-${b.id}`)).toHaveAttribute('aria-current', 'true')
    await page.getByTestId('nav-composition').click()
    await expect(page.getByTestId(`composition-project-${compositionB.id}`)).toHaveAttribute('aria-current', 'true')
    await expect(page.getByTestId('composition-minimum-minutes')).toHaveValue('2')
  } finally { await close(app); await removeProfile(directory) }
})

test('V4 desktop: encrypted APIs, distinct entry requests, background A/B isolation, real media, export and asset survival', async () => {
  const directory = await createProfile('desktop-media')
  let app: ElectronApplication | undefined
  try {
    let running = await launch(directory); app = running.app; let page = running.page
    const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
    const murekaKey = 'fixture-mureka-key-123456789', imageKey = 'fixture-siliconflow-key-123456789'
    await addApi(page, { provider: 'mureka', key: murekaKey }, /测试凭证可用/)
    await addApi(page, { provider: 'siliconflow', key: imageKey }, /测试凭证可用/)
    await expectSecretAbsent(directory, page, [murekaKey, imageKey])
    await page.getByTestId('api-edit-mureka').click()
    const editor = page.getByRole('dialog', { name: '编辑 Mureka', exact: true })
    await expect(editor.getByTestId('api-key')).toHaveValue('')
    await editor.getByTestId('api-save').click() // Blank edit retains only this provider's encrypted key.
    await expect(editor).toHaveCount(0)
    expect((await snapshot(page)).apis.map(api => [api.provider, api.hasKey])).toEqual([['mureka', true], ['siliconflow', true]])
    await page.getByTestId('api-edit-mureka').click()
    await editor.getByTestId('api-clear-key').check(); await editor.getByTestId('api-save').click()
    await expect(editor).toHaveCount(0)
    expect((await snapshot(page)).apis.find(api => api.provider === 'mureka')?.hasKey).toBe(false)
    await page.getByTestId('api-edit-mureka').click()
    await expect(editor.getByTestId('api-test')).toBeDisabled()
    await editor.getByTestId('api-key').fill(murekaKey); await editor.getByTestId('api-save').click()
    await expect(editor).toHaveCount(0)
    expect((await snapshot(page)).apis.find(api => api.provider === 'mureka')?.hasKey).toBe(true)
    expect((await snapshot(page)).requests).toEqual([])
    await page.getByTestId('api-add').click()
    expect(await page.getByTestId('api-provider').locator('option').evaluateAll(options => options.map(option => (option as HTMLOptionElement).value))).not.toEqual(expect.arrayContaining(['mureka', 'siliconflow']))
    await page.keyboard.press('Escape')
    await expect(page.getByTestId('api-add')).toBeFocused()

    const a = await createGeneration(page, '生成 A · 后台请求')
    const first = await addEntry(page, a.id, 'audio')
    let row = page.getByTestId(`entry-${first.id}`)
    await expectApiChoices(row, ['mureka'])
    await row.getByTestId('entry-mode').selectOption('instrumental')
    await row.getByTestId('entry-prompt').fill('第一条：雨夜温柔钢琴，明确独立描述')
    const second = await addEntry(page, a.id, 'audio', first.id)
    await page.getByTestId(`entry-${second.id}`).getByTestId('entry-prompt').fill('第二条：清晨原声吉他，不复制第一条请求')
    const b = await createGeneration(page, '生成 B · 编辑不中断')
    const draftB = await addEntry(page, b.id, 'audio')
    await page.getByTestId(`entry-${draftB.id}`).getByTestId('entry-prompt').fill('B 原始草稿')
    await page.getByTestId(`generation-project-${a.id}`).click()
    await page.getByTestId('generate-all').click()
    await expect(page.getByRole('dialog', { name: '确认本批生成请求', exact: true })).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(page.getByTestId('generate-all')).toBeFocused()
    await submitAll(page, 2, ['Mureka'])
    await page.getByTestId(`generation-project-${b.id}`).click()
    await (await expandEntry(page, draftB.id)).getByTestId('entry-prompt').fill('B 在 A 后台执行时立即编辑，不能被事件覆盖')
    await expect.poll(async () => (await snapshot(page)).requests.filter(request => request.projectId === a.id && request.status === 'succeeded').length).toBe(2)
    await expect(page.getByTestId(`generation-project-${b.id}`)).toHaveAttribute('aria-current', 'true')
    await expect(page.getByTestId(`entry-${draftB.id}`).getByTestId('entry-prompt')).toHaveValue('B 在 A 后台执行时立即编辑，不能被事件覆盖')
    let state = await snapshot(page)
    expect(state.requests.map(request => request.snapshot.prompt)).toEqual(['第一条：雨夜温柔钢琴，明确独立描述', '第二条：清晨原声吉他，不复制第一条请求'])
    expect(state.requests.every(request => request.taskId && request.submittedAt && request.outputs?.length === 1)).toBe(true)
    expect(state.requests.map(request => request.entryId).sort()).toEqual([first.id, second.id].sort())
    expect(new Set(state.requests.map(request => request.taskId)).size).toBe(2)
    expect(state.requests.some(request => request.projectId === b.id)).toBe(false)
    expect(state.entries.every(entry => !('count' in entry.draft))).toBe(true)

    await page.getByTestId(`generation-project-${a.id}`).click()
    const copied = await addEntry(page, a.id, 'audio', first.id)
    expect(copied.requestId).toBeUndefined(); expect(copied.draft.prompt).toBe(state.requests[0].snapshot.prompt)
    await page.getByTestId(`entry-delete-${copied.id}`).click(); await confirmAction(page, '删除未提交条目？')
    row = await expandEntry(page, first.id)
    await expect(row.getByTestId('entry-prompt')).toHaveCount(0) // Submitted content is immutable, not a mutable shared prompt.
    await row.getByRole('button', { name: '试听', exact: true }).click()
    let player = page.getByRole('dialog', { name: '试听音乐', exact: true }).locator('audio')
    await expect.poll(() => player.evaluate((audio: HTMLAudioElement) => audio.readyState)).toBeGreaterThan(0)
    await player.evaluate(async (audio: HTMLAudioElement) => { audio.volume = 0; await audio.play(); audio.currentTime = 3; audio.pause() })
    await expect.poll(() => player.evaluate((audio: HTMLAudioElement) => audio.currentTime)).toBeGreaterThanOrEqual(3)
    await page.keyboard.press('Escape')
    await expect(row.getByRole('button', { name: '试听', exact: true })).toBeFocused()
    const image = await addEntry(page, a.id, 'image')
    const imageRow = page.getByTestId(`entry-${image.id}`)
    await expectApiChoices(imageRow, ['siliconflow'])
    await imageRow.getByTestId('entry-prompt').fill('窗边书桌，夜雨，暖灯，独立图片请求')
    await submitAll(page, 1, ['硅基流动'])
    await expect.poll(async () => (await snapshot(page)).requests.find(request => request.entryId === image.id)?.status).toBe('succeeded')
    state = await snapshot(page)
    const picture = state.assets.find(asset => asset.kind === 'image')!
    expect(picture).toMatchObject({ format: 'png', available: true, usedCount: 0 })
    expect(picture.origins[0]).toMatchObject({ projectId: a.id, entryId: image.id, provider: 'siliconflow', model: 'Qwen/Qwen-Image' })
    await (await expandEntry(page, image.id)).getByRole('button', { name: '查看', exact: true }).click()
    const preview = page.getByRole('dialog', { name: '查看图片', exact: true })
    await expect.poll(() => preview.locator('img').evaluate((element: HTMLImageElement) => element.naturalWidth)).toBeGreaterThan(0)
    const exportPath = path.join(directory, '另存 图片.png'); await nativeSave(app, exportPath)
    await preview.getByRole('button', { name: '另存为', exact: true }).click()
    await expect.poll(() => fileDigest(exportPath)).toBe(digest(await assetBytes(app, picture.id)))
    await page.keyboard.press('Escape')
    const audio = state.assets.find(asset => asset.kind === 'audio')!
    const beforeDelete = digest(await assetBytes(app, audio.id))
    await deleteCurrent(page)
    expect((await snapshot(page)).assets).toHaveLength(2) // Identical synthetic tones deduplicate, but keep both origins.
    expect(digest(await assetBytes(app, audio.id))).toBe(beforeDelete)
    await page.getByTestId('nav-library').click()
    await page.getByTestId(`asset-preview-${audio.id}`).click()
    player = page.getByRole('dialog', { name: '试听音乐', exact: true }).locator('audio')
    await expect.poll(() => player.evaluate((element: HTMLAudioElement) => element.readyState)).toBeGreaterThan(0)
    await page.keyboard.press('Escape')
    await expectSecretAbsent(directory, page, [murekaKey, imageKey])
    expect(errors).toEqual([])
    await close(app); app = undefined
    running = await launch(directory); app = running.app; page = running.page
    const restored = await snapshot(page)
    expect(restored.generationProjects.map(project => project.id)).toEqual([b.id])
    expect(restored.assets.map(asset => asset.id).sort()).toEqual(state.assets.map(asset => asset.id).sort())
    expect(restored.assets.every(asset => asset.available && asset.usedCount === 0)).toBe(true)
    expect(restored.entries.find(entry => entry.id === draftB.id)?.draft.prompt).toBe('B 在 A 后台执行时立即编辑，不能被事件覆盖')
    expect(restored.apis.every(api => api.hasKey)).toBe(true)
  } finally { await close(app); await removeProfile(directory) }
})

test('V4 desktop: unknown music/image stay locked; stopped and interrupted requests require explicit recovery', async () => {
  const directory = await createProfile('desktop-recovery')
  let app: ElectronApplication | undefined
  try {
    let running = await launch(directory); app = running.app; let page = running.page
    await addApi(page, { provider: 'mureka', key: 'fixture-recovery-mureka-key' })
    await addApi(page, { provider: 'siliconflow', key: 'fixture-recovery-image-key' })
    const project = await createGeneration(page, '受理未知与恢复')
    const unknown = await addEntry(page, project.id, 'audio')
    await page.getByTestId(`entry-${unknown.id}`).getByTestId('entry-mode').selectOption('instrumental')
    await page.getByTestId(`entry-${unknown.id}`).getByTestId('entry-prompt').fill('[unknown] 音乐响应丢失')
    const pending = await addEntry(page, project.id, 'audio', unknown.id)
    await page.getByTestId(`entry-${pending.id}`).getByTestId('entry-prompt').fill('尚未发送，必须单独确认')
    await submitAll(page, 2)
    await expect.poll(async () => (await snapshot(page)).requests.map(request => request.status)).toEqual(['unknown', 'paused'])
    let state = await snapshot(page)
    const request = state.requests.find(value => value.entryId === unknown.id)!, paused = state.requests.find(value => value.entryId === pending.id)!
    const unknownRow = await expandEntry(page, unknown.id)
    await expect(unknownRow.getByTestId(`request-resume-${request.id}`)).toHaveCount(0)
    await expect(page.evaluate(id => window.canvas.resumeRequest(id), request.id)).rejects.toThrow('不能恢复')
    await page.getByTestId('project-delete').click()
    await expect(page.getByRole('dialog', { name: '暂不能删除', exact: true }).getByTestId('delete-confirm')).toHaveCount(0)
    await page.keyboard.press('Escape')
    await page.getByTestId('nav-settings').click()
    await page.getByTestId('api-delete-mureka').click()
    await expect(page.getByRole('dialog', { name: '暂不能删除', exact: true }).getByTestId('delete-confirm')).toHaveCount(0)
    await page.keyboard.press('Escape')
    await page.getByTestId('nav-generation').click()
    await page.getByTestId('generation-resume').click()
    // Explicitly stop, rather than authorize the paused request to create a task.
    await expect(page.getByRole('dialog', { name: '确认继续未提交请求', exact: true }).getByTestId('confirm-action')).toBeDisabled()
    await page.keyboard.press('Escape')
    await page.evaluate(id => window.canvas.stopGeneration(id), project.id)
    await expect.poll(async () => (await snapshot(page)).requests.find(value => value.id === paused.id)?.status).toBe('cancelled')
    const image = await addEntry(page, project.id, 'image')
    await page.getByTestId(`entry-${image.id}`).getByTestId('entry-prompt').fill('[unknown] 图片响应丢失')
    await submitAll(page, 1)
    await expect.poll(async () => (await snapshot(page)).requests.find(value => value.entryId === image.id)?.status).toBe('unknown')
    state = await snapshot(page)
    const unknownIds = state.requests.filter(value => value.status === 'unknown').map(value => value.id)
    await close(app); app = undefined
    // This synthetic stopped row now represents a crash after receiving an existing remote task ID.
    await updateStored(directory, 'requests', paused.id, value => { value.status = 'running'; value.taskId = 'fixture-restored-original-id'; value.submittedAt = new Date().toISOString() })
    running = await launch(directory); app = running.app; page = running.page
    await expect.poll(async () => (await snapshot(page)).requests.find(value => value.id === paused.id)?.status).toBe('paused')
    expect((await snapshot(page)).assets).toEqual([]) // Restart itself must neither query nor POST.
    await page.getByTestId('generation-tab-audio').click()
    await (await expandEntry(page, pending.id)).getByTestId(`request-resume-${paused.id}`).click()
    await confirmAction(page, '恢复查询与保存')
    await expect.poll(async () => (await snapshot(page)).requests.find(value => value.id === paused.id)?.status).toBe('succeeded')
    const recovered = await snapshot(page)
    expect(recovered.requests).toHaveLength(3)
    expect(recovered.requests.find(value => value.id === paused.id)?.taskId).toBe('fixture-restored-original-id')
    expect(recovered.requests.filter(value => value.status === 'unknown').map(value => value.id).sort()).toEqual([...unknownIds].sort())
    expect(recovered.assets).toHaveLength(1)
    await (await expandEntry(page, unknown.id)).getByTestId(`request-abandon-${request.id}`).click()
    await confirmAction(page, '放弃追踪此请求？')
    await page.getByTestId('generation-tab-image').click()
    const imageRequest = recovered.requests.find(value => value.entryId === image.id)!
    await (await expandEntry(page, image.id)).getByTestId(`request-abandon-${imageRequest.id}`).click()
    await confirmAction(page, '放弃追踪此请求？')
    await deleteCurrent(page)
    expect((await snapshot(page)).assets).toHaveLength(1)
  } finally { await close(app); await removeProfile(directory) }
})
