import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { WorkspaceStore } from '../../src/renderer/useWorkspace'
import { initialComposition, initialEntry } from '../../src/shared/workbench-schemas'
import type { CompositionProject, GenerationEntry, WorkbenchAPI, WorkbenchSnapshot } from '../../src/shared/workbench-types'

const at = '2026-10-04T12:00:00.000Z'
function entry(id: string, projectId: string): GenerationEntry { return { version: 1, id, projectId, kind: 'audio', revision: 0, createdAt: at, updatedAt: at, draft: initialEntry('audio', 'mureka'), alternatives: {} } }
function composition(id: string): CompositionProject { return { version: 1, id, name: id, revision: 0, createdAt: at, updatedAt: at, draft: initialComposition(), batchIds: [] } }
function fixture() {
  let snapshot: WorkbenchSnapshot = { settings: { version: 5, page: 'generation', mediaRoot: 'C:\\isolated-demo', lastGenerationId: 'A', lastCompositionId: 'C', render: { concurrency: 2, threads: 8, encoder: 'auto' } }, encryptionAvailable: true, apis: [], warnings: [], testMode: true,
    generationProjects: ['A', 'B'].map(id => ({ version: 1, id, name: id, page: 'audio', createdAt: at, updatedAt: at, entryIds: [`${id}-entry`] })), compositionProjects: [composition('C'), composition('D')], entries: [entry('A-entry', 'A'), entry('B-entry', 'B')], requests: [], batches: [], assets: [] }
  const api = {
    bootstrap: vi.fn(async () => structuredClone(snapshot)), updateSettings: vi.fn(async (patch) => { snapshot.settings = { ...snapshot.settings, ...patch }; return structuredClone(snapshot.settings) }),
    updateEntry: vi.fn(async (id, revision, draft, alternatives) => { const current = snapshot.entries.find(e => e.id === id)!; if (revision !== current.revision) throw new Error('revision conflict'); const saved = { ...current, revision: revision + 1, draft, alternatives }; snapshot.entries = snapshot.entries.map(e => e.id === id ? saved : e); return structuredClone(saved) }),
    updateCompositionProject: vi.fn(async (id, revision, patch) => { const current = snapshot.compositionProjects.find(p => p.id === id)!; if (revision !== current.revision) throw new Error('revision conflict'); const saved = { ...current, ...patch, revision: revision + 1 }; snapshot.compositionProjects = snapshot.compositionProjects.map(p => p.id === id ? saved : p); return structuredClone(saved) }),
  } satisfies Partial<WorkbenchAPI>
  const store = new WorkspaceStore(api as unknown as WorkbenchAPI)
  return { store, api, get server() { return snapshot }, set server(value: WorkbenchSnapshot) { snapshot = value } }
}
function deferred<T>() { let resolve!: (value: T) => void; const promise = new Promise<T>(r => { resolve = r }); return { promise, resolve } }

beforeEach(() => vi.useFakeTimers())
afterEach(() => vi.useRealTimers())
describe('V4 renderer keyed draft cache', () => {
  it('loads empty APIs without inventing a configuration or generation project', async () => { const f = fixture(); f.server.generationProjects = []; f.server.entries = []; await f.store.refresh(); expect(f.store.getSnapshot().data?.apis).toEqual([]); expect(f.store.getSnapshot().generationId).toBeUndefined(); expect(f.api.updateEntry).not.toHaveBeenCalled() })
  it('flushes incomplete A draft before switching without copying it into B', async () => { const f = fixture(); await f.store.refresh(); f.store.editEntry('A-entry', { model: '', prompt: '' }); await f.store.selectProject('generation', 'B'); expect(f.api.updateEntry).toHaveBeenCalledWith('A-entry', 0, { model: '', prompt: '' }, {}); expect(f.store.getSnapshot().generationId).toBe('B'); expect(f.store.getSnapshot().data?.entries.find(e => e.id === 'B-entry')?.draft.model).toBe('auto') })
  it('keeps noncurrent dirty drafts across background full snapshots', async () => { const f = fixture(); await f.store.refresh(); await f.store.selectProject('generation', 'B'); f.store.editEntry('A-entry', { model: 'auto', prompt: 'A only' }); f.server.entries[1].draft.prompt = 'B background'; await f.store.refresh(); expect(f.store.getSnapshot().generationId).toBe('B'); expect(f.store.getSnapshot().data?.entries.find(e => e.id === 'A-entry')?.draft.prompt).toBe('A only'); await f.store.flush(); expect(f.server.entries[0].draft.prompt).toBe('A only') })
  it('serializes new typing during a slow save, acknowledging exact local revision only', async () => { const f = fixture(); await f.store.refresh(); const wait = deferred<GenerationEntry>(); f.api.updateEntry.mockImplementationOnce(() => wait.promise); f.store.editEntry('A-entry', { ...initialEntry('audio', 'mureka'), prompt: 'first' }); const saving = f.store.flushEntry('A-entry'); f.store.editEntry('A-entry', { ...initialEntry('audio', 'mureka'), prompt: 'second' }); const first = { ...f.server.entries[0], revision: 1, draft: { ...initialEntry('audio', 'mureka'), prompt: 'first' } }; f.server.entries[0] = first; wait.resolve(first); await saving; expect(f.api.updateEntry).toHaveBeenCalledTimes(2); expect(f.api.updateEntry.mock.calls[1][1]).toBe(1); expect(f.store.getSnapshot().data?.entries[0].draft.prompt).toBe('second') })
  it('does not roll back a newer authoritative revision when an older save response arrives', async () => { const f = fixture(); await f.store.refresh(); const wait = deferred<GenerationEntry>(); f.api.updateEntry.mockImplementationOnce(() => wait.promise); f.store.editEntry('A-entry', { ...initialEntry('audio', 'mureka'), prompt: 'sent' }); const saving = f.store.flushEntry('A-entry'); f.server.entries[0] = { ...f.server.entries[0], revision: 2, draft: { ...initialEntry('audio', 'mureka'), prompt: 'newer server' } }; await f.store.refresh(); wait.resolve({ ...f.server.entries[0], revision: 1, draft: { ...initialEntry('audio', 'mureka'), prompt: 'sent' } }); await saving; expect(f.store.getSnapshot().data?.entries[0].revision).toBe(2); expect(f.store.getSnapshot().data?.entries[0].draft.prompt).toBe('newer server') })
  it('preserves long text and per-provider alternatives with legal long defaults', async () => { const f = fixture(); await f.store.refresh(); const prompt = '描述'.repeat(3000), lyrics = '歌词'.repeat(3000); f.store.editEntry('A-entry', { ...initialEntry('audio', 'mureka'), prompt, lyrics }); f.store.changeProvider('A-entry', 'kie'); expect(f.store.getSnapshot().data?.entries[0].draft).toMatchObject({ prompt, lyrics, seconds: 360, mode: 'song' }); f.store.changeProvider('A-entry', 'acestep'); expect(f.store.getSnapshot().data?.entries[0].draft.seconds).toBe(600); f.store.changeProvider('A-entry', 'mureka'); await f.store.flush(); expect(f.server.entries[0].draft.prompt).toBe(prompt); expect(f.server.entries[0].alternatives.kie?.lyrics).toBe(lyrics); expect(f.server.entries[0].draft).not.toHaveProperty('count') })
  it('retains failed drafts and prevents switching until a successful flush', async () => { const f = fixture(); await f.store.refresh(); f.api.updateEntry.mockRejectedValueOnce(new Error('disk full')); f.store.editEntry('A-entry', { model: '', prompt: 'retained' }); await expect(f.store.selectProject('generation', 'B')).rejects.toThrow('disk full'); expect(f.store.getSnapshot().generationId).toBe('A'); expect(f.store.getSnapshot().saves['A-entry'].phase).toBe('error'); await f.store.selectProject('generation', 'B'); expect(f.server.entries[0].draft.prompt).toBe('retained') })
  it('rejects a response for the wrong ID rather than installing another project draft', async () => { const f = fixture(); await f.store.refresh(); f.api.updateEntry.mockResolvedValueOnce(f.server.entries[1]); f.store.editEntry('A-entry', { model: '', prompt: 'A' }); await expect(f.store.flushEntry('A-entry')).rejects.toThrow('标识不匹配'); expect(f.store.getSnapshot().data?.entries[0].draft.prompt).toBe('A') })
  it('persists composition selections independently by ID and revision', async () => { const f = fixture(); await f.store.refresh(); f.store.editComposition('C', { ...initialComposition(), audioIds: ['only-C'] }); await f.store.selectProject('composition', 'D'); expect(f.server.compositionProjects[0].draft.audioIds).toEqual(['only-C']); expect(f.server.compositionProjects[1].draft.audioIds).toEqual([]); expect(f.store.getSnapshot().generationId).toBe('A'); expect(f.api.updateCompositionProject.mock.calls[0][1]).toBe(0) })
  it('discards an in-flight snapshot invalidated by a dirty notification', async () => { const f = fixture(); await f.store.refresh(); const wait = deferred<WorkbenchSnapshot>(); f.api.bootstrap.mockImplementationOnce(() => wait.promise); const old = structuredClone(f.server); const first = f.store.refresh(); f.server.entries[1].draft.prompt = 'new snapshot'; const second = f.store.refresh(); wait.resolve(old); await Promise.all([first, second]); expect(f.store.getSnapshot().data?.entries[1].draft.prompt).toBe('new snapshot'); expect(f.store.getSnapshot().generationId).toBe('A') })
  it('removes deleted draft caches so subsequent navigation cannot write deleted records', async () => { const f = fixture(); await f.store.refresh(); f.store.editEntry('A-entry', { model: '', prompt: 'delete me' }); f.server.entries = f.server.entries.filter(e => e.id !== 'A-entry'); await f.store.refresh(); await f.store.flush(); expect(f.api.updateEntry).not.toHaveBeenCalled(); expect(f.store.getSnapshot().saves['A-entry']).toBeUndefined() })
})
